The property '#/lupdates/0/package-ecosystem' value "" did not match one of the following values: npm, bundler, composer, maven, mix, cargo, gradle, nuget, gomod, docker, elm, gitsubmodule, github-actions, pip, terraform, pub

The property '#/' did not contain a required property of 'version'
The property '#/' did not contain a required property of 'updates'
The property '#/' contains additional properties ["The property '#/updates/0/package-ecosystem' value \"\" did not match one of the following values"] outside of the schema when none are allowed
